"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']

os.environ['TNS_ADMIN'] = config('TNS_ADMIN')
# python-oracledb는 기본 Thin 모드이므로 init_oracle_client() 호출 불필요

# data_router (Go) — Oracle ADB 접근은 이 서비스 경유로만. services/main 의
# DATA_ROUTER_* 환경변수와 동일한 이름을 그대로 사용.
DATA_ROUTER_URL = config('DATA_ROUTER_URL', default='http://localhost:8080')
DATA_ROUTER_TOKEN = config('DATA_ROUTER_TOKEN', default='')
DATA_ROUTER_CALLER = config('DATA_ROUTER_CALLER', default='django-main')
DATA_ROUTER_TIMEOUT_MS = config('DATA_ROUTER_TIMEOUT_MS', default=15000, cast=int)

# shed 어드민(외부 Vercel 프로젝트)이 X-Shed-Key 헤더로 인증하는 내부 공유키.
# services/main 의 SHED_INTERNAL_KEY 와 동일한 값이어야 shed 쪽에서 붙일 수 있음.
SHED_INTERNAL_KEY = config('SHED_INTERNAL_KEY', default='')

# JWT 발급/검증 — services/main 의 config.js 와 동일한 env 이름.
# ACCESS/REFRESH_TTL은 서버 기동 시 한 번만 읽힘 (AUTH_CONFIGS.ACCESS_TTL과
# 달리 요청마다 다시 읽지 않음 — 원본 동작 그대로).
JWT_SECRET = config('JWT_SECRET')
JWT_ACCESS_TTL = config('JWT_ACCESS_TTL', default='15m')
JWT_REFRESH_TTL = config('JWT_REFRESH_TTL', default='30d')

# 사명의 길 비밀번호 (admin-unlock 라우트 포팅 전까지는 미사용).
ADMIN_PASSWORD = config('ADMIN_PASSWORD', default='1440')

# AUTH_CONFIGS / ROLES 조회 시 쓰는 지역 — prod 시드 데이터가 'college' 기준.
REGION_ID = config('REGION_ID', default='college')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Django 자체 내부 테이블(admin/auth/sessions)만 여기 저장. 실제 서비스
# 데이터는 Oracle ADB — data_router 경유로만 접근 (api/clients/data_router.py).
# wallet의 ewallet.pem이 비밀번호로 잠겨 있어 Django ORM의 직접 Oracle 연결이
# 막히므로(runserver 기동 시 마이그레이션 체크가 무한 대기), sqlite로 분리.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
