-- ================================================================
-- 07_sarang.sql — Sarang 도메인 (재설계, PERSONAL_INFO/PROSPECTS/
-- PROSPECT_TM_LOGS/PROSPECT_HABJAEYANG/PROSPECT_MEETINGS 대체)
-- ================================================================
-- schema-spec.md(CRM Database Schema Specification, Sarang Domain)의
-- 5개 회귀 항목 검토·확정 결과를 그대로 구현.
--
--  1. PII 분리 유지        → SARANG_PERSONAL_INFO 별도 테이블(스펙 원안은
--                            NAME/PHONE을 SARANG에 직접 저장 — 기존
--                            PERSONAL_INFO처럼 분리하기로 확정)
--  2. 4축 상태 유지        → SARANG.STAGE(퍼널)에 IS_DROPPED/APPROVAL_STATUS/
--                            TM_STATUS 3개 축 추가, 스펙 원안의 CURRENT_PROCESS
--                            (STAGE와 값이 겹치는 중복 컬럼)는 제거
--  3. 합재양 1:N 유지      → SARANG_HAB_JAE_YANG의 PK를 SARANG_ID(1:1)에서
--                            HAB_JAE_YANG_ID(surrogate)로, IS_ACTIVE 플래그 추가
--  4. 밀림 이력(변경 없음)  → SARANG_MATCH_HISTORIES.ATTEMPT_COUNT는 밀릴 때마다
--                            새 행 INSERT(앱 레벨 규약) — UPDATE 아님, 스펙 그대로
--  5. TM_PHASE/CATEGORY    → TM_LOGS는 통화 전용으로 스코프 유지, 통화 아닌
--     병합 문제 해결          이벤트(문자 발송/합재양 작성)는 SARANG_ACTIVITY_LOGS 신설
--
-- 감사컬럼(CREATED_AT 등)·소프트 삭제(DELETED_AT)는 스펙엔 없지만 이 프로젝트
-- 기존 테이블 전체가 따르는 관례라 SARANG에는 동일하게 유지(그 외 로그성
-- 테이블은 append-only라 원본 PROSPECT_HISTORY/PROSPECT_TM_LOGS처럼 생략).
-- ================================================================

CREATE TABLE SARANG_PERSONAL_INFO (
  PERSONAL_INFO_ID   VARCHAR2(64 CHAR)            PRIMARY KEY,
  NAME               VARCHAR2(50 CHAR)            NOT NULL,
  PHONE              VARCHAR2(20 CHAR)            NOT NULL,
  PHONE_NORMALIZED   VARCHAR2(20 CHAR)            NOT NULL,
  RESIDENCE_STATION  VARCHAR2(100 CHAR),
  CREATED_AT         TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT CK_SPI_PHONE_NORM CHECK (REGEXP_LIKE(PHONE_NORMALIZED, '^[0-9]+$'))
);

CREATE INDEX IX_SPI_PHONE_NORM ON SARANG_PERSONAL_INFO (PHONE_NORMALIZED);

COMMENT ON TABLE SARANG_PERSONAL_INFO IS '사랑이 PII 분리(이름/연락처). PERSONAL_INFO 대체';
COMMENT ON COLUMN SARANG_PERSONAL_INFO.PERSONAL_INFO_ID IS 'SHA-256(name+phone) hex — 재신청 시 동일 인물 자동 연결';

CREATE TABLE SARANG (
  SARANG_ID           VARCHAR2(50 CHAR)            PRIMARY KEY,
  PERSONAL_INFO_ID    VARCHAR2(64 CHAR)            NOT NULL,
  INFLOW_MEMBER_ID    VARCHAR2(50 CHAR)            NOT NULL,
  AGE                 NUMBER(3),
  MBTI                VARCHAR2(10 CHAR),
  STAGE               VARCHAR2(30 CHAR)            NOT NULL CHECK (STAGE IN (
                        '유입','티엠','만픽','합재양','재가','매칭','상따','성홀','성따','복방','센'
                      )),
  RECRUITMENT_TYPE    VARCHAR2(20 CHAR)            NOT NULL CHECK (RECRUITMENT_TYPE IN ('OFFLINE','ONLINE')),
  INFLOW_DATE         TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
  CURRENT_PROCESS     VARCHAR2(30 CHAR)            CHECK (CURRENT_PROCESS IN (
                        '합재양','재가대기','교사배정','매칭대기','매칭완료'
                      )),
  CREATED_AT          TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY          VARCHAR2(50 CHAR)            NOT NULL,
  UPDATED_BY          VARCHAR2(50 CHAR)            NOT NULL,
  DELETED_AT          TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT FK_SARANG_PI     FOREIGN KEY (PERSONAL_INFO_ID) REFERENCES SARANG_PERSONAL_INFO(PERSONAL_INFO_ID),
  CONSTRAINT FK_SARANG_INFLOW FOREIGN KEY (INFLOW_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE INDEX IX_SARANG_STAGE   ON SARANG (STAGE, UPDATED_AT DESC);
CREATE INDEX IX_SARANG_INFLOW  ON SARANG (INFLOW_MEMBER_ID, UPDATED_AT DESC);
CREATE INDEX IX_SARANG_PI      ON SARANG (PERSONAL_INFO_ID);

COMMENT ON TABLE  SARANG               IS '사랑이(대상자) 메인 테이블. PROSPECTS 대체';
COMMENT ON COLUMN SARANG.STAGE           IS '퍼널 진행 단계 — 스펙 원안 그대로';
COMMENT ON COLUMN SARANG.CURRENT_PROCESS IS '현재 진행 세부 단계 — 스펙 원안 그대로. 합재양 이후에만 의미 있어서 그 전엔 NULL';

CREATE TABLE SARANG_INFLOW_DETAILS (
  SARANG_ID        VARCHAR2(50 CHAR)            PRIMARY KEY,
  REGION_NAME      VARCHAR2(50 CHAR),
  REACTION         VARCHAR2(100 CHAR),
  LOCATION         VARCHAR2(100 CHAR),
  ENV                  VARCHAR2(50 CHAR),
  INTRODUCER_MEMBER_ID VARCHAR2(50 CHAR),
  HELPER_MEMBER_IDS    VARCHAR2(300 CHAR),
  TM_RESERVED_AT   TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT FK_SID_SARANG FOREIGN KEY (SARANG_ID) REFERENCES SARANG(SARANG_ID) ON DELETE CASCADE
);

COMMENT ON TABLE SARANG_INFLOW_DETAILS IS '최초 유입 시점 세부정보 (1:1). ENV/INTRODUCER_MEMBER_ID는 SARANG_INTAKE_QUEUE에서 이관받기 시 그대로 복사됨';
COMMENT ON COLUMN SARANG_INFLOW_DETAILS.INTRODUCER_MEMBER_ID IS '유입자의 MEMBERS.MEMBER_ID. 이름 텍스트는 안 저장하고 표시할 때 MEMBERS 조인으로 얻음(FK 강제는 안 함 — shed가 이관 응답을 안 보므로 강제 FK 위반 시 이관 전체가 조용히 유실될 위험 방지)';
COMMENT ON COLUMN SARANG_INFLOW_DETAILS.HELPER_MEMBER_IDS    IS '유입자 추첨에서 낙첨된 조력자들의 MEMBER_ID — 콤마 구분. FK 강제 안 함(위와 동일 이유)';

CREATE TABLE TM_LOGS (
  TM_ID             VARCHAR2(50 CHAR)            PRIMARY KEY,
  SARANG_ID         VARCHAR2(50 CHAR)            NOT NULL,
  CALLER_MEMBER_ID  VARCHAR2(50 CHAR)            NOT NULL,
  TOOL              VARCHAR2(50 CHAR),
  RESULT            VARCHAR2(30 CHAR)            NOT NULL CHECK (RESULT IN (
                      '부재중','예약 티엠','만남 픽스','비합','거절','무효'
                    )),
  SUB_REASON        VARCHAR2(50 CHAR),
  RESERVED_TM_AT    TIMESTAMP(6) WITH TIME ZONE,
  CALL_STARTED_AT   TIMESTAMP(6) WITH TIME ZONE,
  CALL_ENDED_AT     TIMESTAMP(6) WITH TIME ZONE,
  MEMO              CLOB,
  CREATED_AT        TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_TL_SARANG FOREIGN KEY (SARANG_ID)        REFERENCES SARANG(SARANG_ID) ON DELETE CASCADE,
  CONSTRAINT FK_TL_CALLER FOREIGN KEY (CALLER_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE INDEX IX_TL_SARANG_TIME ON TM_LOGS (SARANG_ID, CREATED_AT DESC);

COMMENT ON TABLE TM_LOGS IS '티엠 시도 및 통화 이력. 통화 전용 — 통화 아닌 이벤트는 SARANG_ACTIVITY_LOGS';

CREATE TABLE SARANG_ACTIVITY_LOGS (
  ACTIVITY_ID       VARCHAR2(50 CHAR)            PRIMARY KEY,
  SARANG_ID         VARCHAR2(50 CHAR)            NOT NULL,
  ACTOR_MEMBER_ID   VARCHAR2(50 CHAR)            NOT NULL,
  EVENT_TYPE        VARCHAR2(30 CHAR)            NOT NULL CHECK (EVENT_TYPE IN (
                      '선문자발송','부재중문자발송','합재양작성','재가처리','반려처리'
                    )),
  CONTENT           CLOB,
  CREATED_AT        TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SAL_SARANG FOREIGN KEY (SARANG_ID)       REFERENCES SARANG(SARANG_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SAL_ACTOR  FOREIGN KEY (ACTOR_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE INDEX IX_SAL_SARANG_TIME ON SARANG_ACTIVITY_LOGS (SARANG_ID, CREATED_AT DESC);

COMMENT ON TABLE SARANG_ACTIVITY_LOGS IS '통화가 아닌 TM 관련 이벤트(문자 발송, 합재양 작성 등). TM_LOGS와 시간순으로 합쳐서 타임라인 구성';

CREATE TABLE SARANG_HAB_JAE_YANG (
  HAB_JAE_YANG_ID       VARCHAR2(50 CHAR)            PRIMARY KEY,
  SARANG_ID             VARCHAR2(50 CHAR)            NOT NULL,
  IS_ACTIVE             NUMBER(1)                    DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
  GUIDE_MEMBER_ID       VARCHAR2(50 CHAR),
  CALLER_MEMBER_ID      VARCHAR2(50 CHAR),
  TEACHER_MEMBER_ID     VARCHAR2(50 CHAR),
  ROUTE                 VARCHAR2(50 CHAR),
  TOOL                  VARCHAR2(50 CHAR),
  IS_VERBAL_MEET        NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (IS_VERBAL_MEET IN (0,1)),
  MATCH_SCHEDULED_AT    TIMESTAMP(6) WITH TIME ZONE,
  MATCH_LOCATION        VARCHAR2(100 CHAR),
  GWACHEON_TRAVEL_TIME  NUMBER(5),
  GWACHEON_TRANSFER_COUNT NUMBER(3),
  CENTER_TRAVEL_TIME    NUMBER(5),
  CENTER_TRANSFER_COUNT NUMBER(3),
  SCHOOL_MAJOR_JOB      VARCHAR2(100 CHAR),
  SCHEDULE              VARCHAR2(100 CHAR),
  ENVIRONMENT_1Y        VARCHAR2(255 CHAR),
  APPLICATION_PURPOSE   VARCHAR2(255 CHAR),
  SELF_IMAGE            VARCHAR2(255 CHAR),
  DESIRED_IMAGE         VARCHAR2(255 CHAR),
  CHARACTER_NOTE        VARCHAR2(255 CHAR),
  ALERT_NOTE            VARCHAR2(255 CHAR),
  DISTANCE_BURDEN       VARCHAR2(255 CHAR),
  HAS_CENTER_ENV        NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (HAS_CENTER_ENV IN (0,1)),
  IS_TAKING_MEDS        NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (IS_TAKING_MEDS IN (0,1)),
  HAS_MENTAL_ILLNESS    NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (HAS_MENTAL_ILLNESS IN (0,1)),
  HAS_REPLIED           NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (HAS_REPLIED IN (0,1)),
  IS_WINDOW_OPENED      NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (IS_WINDOW_OPENED IN (0,1)),
  IS_JAE_GA             NUMBER(1)                    DEFAULT 0 NOT NULL CHECK (IS_JAE_GA IN (0,1)),
  APPROVAL_STATUS       VARCHAR2(20)                 DEFAULT 'pending' NOT NULL
                        CHECK (APPROVAL_STATUS IN ('pending','approved','rejected')),
  REJECT_REASON         VARCHAR2(500),
  TEACHER_NAME_OVERRIDE VARCHAR2(100),
  CREATED_AT            TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SHJY_SARANG  FOREIGN KEY (SARANG_ID)         REFERENCES SARANG(SARANG_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SHJY_GUIDE   FOREIGN KEY (GUIDE_MEMBER_ID)   REFERENCES MEMBERS(MEMBER_ID),
  CONSTRAINT FK_SHJY_CALLER  FOREIGN KEY (CALLER_MEMBER_ID)  REFERENCES MEMBERS(MEMBER_ID),
  CONSTRAINT FK_SHJY_TEACHER FOREIGN KEY (TEACHER_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE INDEX IX_SHJY_SARANG ON SARANG_HAB_JAE_YANG (SARANG_ID, CREATED_AT DESC);
-- 사랑이 1명당 활성(IS_ACTIVE=1) 합재양은 최대 1개 — 재매칭 시 이전 행은 0으로 내리고 새 행 추가
CREATE UNIQUE INDEX UX_SHJY_ACTIVE ON SARANG_HAB_JAE_YANG (
  CASE WHEN IS_ACTIVE = 1 THEN SARANG_ID END
);

COMMENT ON TABLE SARANG_HAB_JAE_YANG IS '합재양(매칭/상담 후 신상·환경정보). SARANG:HJY = 1:N — IS_ACTIVE=1 인 행이 현재본. PROSPECT_HABJAEYANG 대체';
COMMENT ON COLUMN SARANG_HAB_JAE_YANG.APPROVAL_STATUS IS '합재양 재가 상태 — pending(대기)/approved(재가)/rejected(반려). 승인 시 SARANG.STAGE도 합재양→재가로 전환';
COMMENT ON COLUMN SARANG_HAB_JAE_YANG.REJECT_REASON    IS '반려 사유(자유 텍스트) — status=rejected일 때만 의미 있음';
COMMENT ON COLUMN SARANG_HAB_JAE_YANG.TEACHER_NAME_OVERRIDE IS '타지역 교사처럼 MEMBERS에 없는 이름 저장용 — TEACHER_MEMBER_ID 없을 때만 씀';

CREATE TABLE SARANG_MATCH_HISTORIES (
  MATCH_ID          VARCHAR2(50 CHAR)            PRIMARY KEY,
  SARANG_ID         VARCHAR2(50 CHAR)            NOT NULL,
  TEACHER_MEMBER_ID VARCHAR2(50 CHAR),
  MATCH_DEGREE      NUMBER(3)                    DEFAULT 1 NOT NULL,
  ATTEMPT_COUNT     NUMBER(3)                    DEFAULT 1 NOT NULL,
  MATCHED_AT        TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
  MATCH_LOCATION    VARCHAR2(100 CHAR),
  STATUS            VARCHAR2(30 CHAR)            NOT NULL CHECK (STATUS IN ('SCHEDULED','DELAYED','IN_PROGRESS','FINISHED')),
  RESULT            VARCHAR2(30 CHAR)            CHECK (RESULT IN ('취소','밀림','비합','탈락','2차 만남','상담 따기')),
  SUB_REASON        VARCHAR2(100 CHAR),
  CREATED_AT        TIMESTAMP(6) WITH TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_SMH_SARANG  FOREIGN KEY (SARANG_ID)         REFERENCES SARANG(SARANG_ID) ON DELETE CASCADE,
  CONSTRAINT FK_SMH_TEACHER FOREIGN KEY (TEACHER_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
);

CREATE INDEX IX_SMH_SARANG_DEGREE ON SARANG_MATCH_HISTORIES (SARANG_ID, MATCH_DEGREE, ATTEMPT_COUNT);

COMMENT ON TABLE  SARANG_MATCH_HISTORIES        IS '교사 매칭 차수별 결과·밀림 이력. append-only — 밀릴 때마다 새 행 INSERT(ATTEMPT_COUNT 증가), UPDATE로 덮어쓰지 않음';
COMMENT ON COLUMN SARANG_MATCH_HISTORIES.ATTEMPT_COUNT IS '차수 내 시도 횟수. 이전 시도 행은 그대로 두고 새 행을 추가하는 방식으로 이력 보존';

COMMIT;
