-- shed 이관 자유입력(반응/환경/유입장소)이 칸보다 길면 웹훅이 ORA-12899로 500 나서 이관이 통째로 빠짐 — 늘리기만 함(기존 데이터 영향 없음)
ALTER TABLE SARANG_INTAKE_QUEUE MODIFY (REACTION VARCHAR2(1000 CHAR), ENV VARCHAR2(500 CHAR), LOCATION VARCHAR2(300 CHAR));
ALTER TABLE SARANG_INFLOW_DETAILS MODIFY (REACTION VARCHAR2(1000 CHAR), ENV VARCHAR2(500 CHAR), LOCATION VARCHAR2(300 CHAR));
