-- shed 페이지에 신청한 시각(시트 A열) — 합당한자 "유입날 4일 지나면 전 지역 공개" 기준. GAS가 이관할 때 appliedAt으로 보냄
ALTER TABLE SARANG_INTAKE_QUEUE ADD (APPLIED_AT TIMESTAMP(6) WITH TIME ZONE);
ALTER TABLE SARANG_INFLOW_DETAILS ADD (APPLIED_AT TIMESTAMP(6) WITH TIME ZONE);
