"""main(Express) 라우트 구조를 그대로 옮긴 URL 스캐폴딩. /api, /internal, /internal/cron 3개 목록으로 분리."""
from django.http import JsonResponse
from django.urls import path

from .views import admin_audit_log
from .views import admin_users
from .views import area_score
from .views import assets
from .views import auth
from .views import board
from .views import cron_internal
from .views import daily_report
from .views import dolyo
from .views import feedback
from .views import intake_sync
from .views import intake_webhook
from .views import internal_telegram
from .views import locks
from .views import ministry
from .views import prayer
from .views import preview
from .views import schedule
from .views import shared_leads_claim
from .views import shared_leads_notify
from .views import shed_report
from .views import shed_users
from .views import sheet_sync
from .views import sheets
from .views import stats
from .views import storage
from .views import system
from .views import teams
from .views import telegram_pair
from .views import telegram_pair_internal


def health(request):
    return JsonResponse({"ok": True, "service": "main"})


api_urlpatterns = [
    path('ping', system.ping, name='system_ping'),
    path('healthz', system.healthz, name='system_healthz'),
    path('login', auth.login, name='auth_login'),
    path('refresh', auth.refresh, name='auth_refresh'),
    path('admin-unlock', auth.admin_unlock, name='auth_admin_unlock'),
    path('auth-config/get', auth.auth_config_get, name='auth_auth_config_get'),
    path('auth-config/save', auth.auth_config_save, name='auth_auth_config_save'),
    path('get-sheet-configs', sheets.get_sheet_configs, name='sheets_get_sheet_configs'),
    path('get-sheet-prospects', sheets.get_sheet_prospects, name='sheets_get_sheet_prospects'),
    path('fetch-sheet-data', sheets.fetch_sheet_data, name='sheets_fetch_sheet_data'),
    path('test-sheet-access', sheets.test_sheet_access, name='sheets_test_sheet_access'),
    path('save-sheet-config', sheets.save_sheet_config, name='sheets_save_sheet_config'),
    path('delete-sheet-config', sheets.delete_sheet_config, name='sheets_delete_sheet_config'),
    path('sheet-sync/trigger', sheets.sheet_sync_trigger, name='sheets_sheet_sync_trigger'),
    path('send-sheet-dashboard', sheets.send_sheet_dashboard, name='sheets_send_sheet_dashboard'),
    path('sheet-sync/progress', sheets.sheet_sync_progress, name='sheets_sheet_sync_progress'),
    path('manage-sheet-config-order', sheets.manage_sheet_config_order, name='sheets_manage_sheet_config_order'),
    path('update-import-status', sheets.update_import_status, name='sheets_update_import_status'),
    path('delete-import-status', sheets.delete_import_status, name='sheets_delete_import_status'),
    path('tm-sheet/my-configs', sheets.tm_sheet_my_configs, name='sheets_tm_sheet_my_configs'),
    path('tm-sheet/events', sheets.tm_sheet_events, name='sheets_tm_sheet_events'),
    path('tm-sheet/rows', sheets.tm_sheet_rows, name='sheets_tm_sheet_rows'),
    path('tm-sheet/add-row', sheets.tm_sheet_add_row, name='sheets_tm_sheet_add_row'),
    path('tm-sheet/save-row', sheets.tm_sheet_save_row, name='sheets_tm_sheet_save_row'),
    path('tm-sheet/delete-row', sheets.tm_sheet_delete_row, name='sheets_tm_sheet_delete_row'),
    path('sheet-view/rows', sheets.sheet_view_rows, name='sheets_sheet_view_rows'),
    path('sheet-view/update-cell', sheets.sheet_view_update_cell, name='sheets_sheet_view_update_cell'),
    path('sheet-view/append-row', sheets.sheet_view_append_row, name='sheets_sheet_view_append_row'),
    path('sheet-view/col-validations', sheets.sheet_view_col_validations, name='sheets_sheet_view_col_validations'),
    path('sheet-view/delete-row', sheets.sheet_view_delete_row, name='sheets_sheet_view_delete_row'),
    path('get-assets', assets.get_assets, name='assets_get_assets'),
    path('get-matching-history', assets.get_matching_history, name='assets_get_matching_history'),
    path('update-manager', assets.update_manager, name='assets_update_manager'),
    path('update-prospect-info', assets.update_prospect_info, name='assets_update_prospect_info'),
    path('search-prospects', assets.search_prospects, name='assets_search_prospects'),
    path('update-match', assets.update_match, name='assets_update_match'),
    path('submit-result', assets.submit_result, name='assets_submit_result'),
    path('delete-log', assets.delete_log, name='assets_delete_log'),
    path('toggle-hj-status', assets.toggle_hj_status, name='assets_toggle_hj_status'),
    path('edit-match', assets.edit_match, name='assets_edit_match'),
    path('update-approval', assets.update_approval, name='assets_update_approval'),
    path('postpone-meeting', assets.postpone_meeting, name='assets_postpone_meeting'),
    path('clone-row', assets.clone_row, name='assets_clone_row'),
    path('get-center-assets', assets.get_center_assets, name='assets_get_center_assets'),
    path('submit-habjaeyang-new', assets.submit_habjaeyang_new, name='assets_submit_habjaeyang_new'),
    path('habjaeyang-dup-resolve', assets.habjaeyang_dup_resolve, name='assets_habjaeyang_dup_resolve'),
    path('shed-call-status', assets.shed_call_status, name='assets_shed_call_status'),
    path('shed-presence-leave', assets.shed_presence_leave, name='assets_shed_presence_leave'),
    path('shed-call-start', assets.shed_call_start, name='assets_shed_call_start'),
    path('shed-call-end', assets.shed_call_end, name='assets_shed_call_end'),
    path('shed-note-save', assets.shed_note_save, name='assets_shed_note_save'),
    path('get-tm-script', assets.get_tm_script, name='assets_get_tm_script'),
    path('save-tm-script', assets.save_tm_script, name='assets_save_tm_script'),
    path('shed-register', assets.shed_register, name='assets_shed_register'),
    path('shed-reject-duplicate', assets.shed_reject_duplicate, name='assets_shed_reject_duplicate'),
    path('get-shed-prospects', assets.get_shed_prospects, name='assets_get_shed_prospects'),
    path('run-shed-gacha', assets.run_shed_gacha, name='assets_run_shed_gacha'),
    path('cancel-shed-habjaeyang', assets.cancel_shed_habjaeyang, name='assets_cancel_shed_habjaeyang'),
    path('shed-reject', assets.shed_reject, name='assets_shed_reject'),
    path('shed-revive', assets.shed_revive, name='assets_shed_revive'),
    path('shed/lookup-teams', assets.shed_lookup_teams, name='assets_shed_lookup_teams'),
    path('shed-pending-reject', assets.shed_pending_reject, name='assets_shed_pending_reject'),
    path('shed-webhook', assets.shed_webhook, name='assets_shed_webhook'),
    path('shed/pending-list', assets.shed_pending_list, name='assets_shed_pending_list'),
    path('daily-report/list-names', daily_report.daily_report_list_names, name='daily_report_daily_report_list_names'),
    path('daily-report/get', daily_report.daily_report_get, name='daily_report_daily_report_get'),
    path('daily-report', daily_report.daily_report, name='daily_report_daily_report'),
    path('daily-report/search-reg', daily_report.daily_report_search_reg, name='daily_report_daily_report_search_reg'),
    path('daily-report/add-reg-entry', daily_report.daily_report_add_reg_entry, name='daily_report_daily_report_add_reg_entry'),
    path('get-my-plan', daily_report.get_my_plan, name='daily_report_get_my_plan'),
    path('update-today-plan', daily_report.update_today_plan, name='daily_report_update_today_plan'),
    path('get-missed-executions', daily_report.get_missed_executions, name='daily_report_get_missed_executions'),
    path('get-plan-execution', daily_report.get_plan_execution, name='daily_report_get_plan_execution'),
    path('update-plan-execution', daily_report.update_plan_execution, name='daily_report_update_plan_execution'),
    path('batch-update-executions', daily_report.batch_update_executions, name='daily_report_batch_update_executions'),
    path('weekly-template/get', daily_report.weekly_template_get, name='daily_report_weekly_template_get'),
    path('weekly-template/save-all', daily_report.weekly_template_save_all, name='daily_report_weekly_template_save_all'),
    path('get-audit-logs', daily_report.get_audit_logs, name='daily_report_get_audit_logs'),
    path('daily-report/reflections', daily_report.daily_report_reflections, name='daily_report_daily_report_reflections'),
    path('area-score/today', area_score.area_score_today, name='area_score_area_score_today'),
    path('area-score/toggle', area_score.area_score_toggle, name='area_score_area_score_toggle'),
    path('area-score/unlock-requests', area_score.area_score_unlock_requests, name='area_score_area_score_unlock_requests'),
    path('area-score/unlock-requests/list', area_score.area_score_unlock_requests_list, name='area_score_area_score_unlock_requests_list'),
    path('area-score/unlock-requests/<str:id>/complete', area_score.area_score_unlock_requests_id_complete, name='area_score_area_score_unlock_requests_id_complete'),
    path('area-score/mission/complete', area_score.area_score_mission_complete, name='area_score_area_score_mission_complete'),
    path('area-score/area-detail', area_score.area_score_area_detail, name='area_score_area_score_area_detail'),
    path('area-score/area/add', area_score.area_score_area_add, name='area_score_area_score_area_add'),
    path('area-score/area/remove-last', area_score.area_score_area_remove_last, name='area_score_area_score_area_remove_last'),
    path('get-week-start-dow', stats.get_week_start_dow, name='stats_get_week_start_dow'),
    path('set-week-start-global', stats.set_week_start_global, name='stats_set_week_start_global'),
    path('set-week-start-personal', stats.set_week_start_personal, name='stats_set_week_start_personal'),
    path('my-archive', stats.my_archive, name='stats_my_archive'),
    path('my-goal', stats.my_goal, name='stats_my_goal'),
    path('get-stats-password', stats.get_stats_password, name='stats_get_stats_password'),
    path('get-personal-stats', stats.get_personal_stats, name='stats_get_personal_stats'),
    path('get-comprehensive-stats', stats.get_comprehensive_stats, name='stats_get_comprehensive_stats'),
    path('get-weekly-record', stats.get_weekly_record, name='stats_get_weekly_record'),
    path('get-telegram-goals', stats.get_telegram_goals, name='stats_get_telegram_goals'),
    path('save-telegram-goals', stats.save_telegram_goals, name='stats_save_telegram_goals'),
    path('send-morning-briefing', stats.send_morning_briefing, name='stats_send_morning_briefing'),
    path('send-weekly-report', stats.send_weekly_report, name='stats_send_weekly_report'),
    path('send-comparison-report', stats.send_comparison_report, name='stats_send_comparison_report'),
    path('get-teams', teams.get_teams, name='teams_get_teams'),
    path('get-team-areas', teams.get_team_areas, name='teams_get_team_areas'),
    path('connect-telegram', teams.connect_telegram, name='teams_connect_telegram'),
    path('get-tool-configs', teams.get_tool_configs, name='teams_get_tool_configs'),
    path('save-tool-config', teams.save_tool_config, name='teams_save_tool_config'),
    path('delete-tool-config', teams.delete_tool_config, name='teams_delete_tool_config'),
    path('get-path-configs', teams.get_path_configs, name='teams_get_path_configs'),
    path('save-path-config', teams.save_path_config, name='teams_save_path_config'),
    path('delete-path-config', teams.delete_path_config, name='teams_delete_path_config'),
    path('get-return-home-config', teams.get_return_home_config, name='teams_get_return_home_config'),
    path('save-return-home-config', teams.save_return_home_config, name='teams_save_return_home_config'),
    path('get-auto-reject-config', teams.get_auto_reject_config, name='teams_get_auto_reject_config'),
    path('save-auto-reject-config', teams.save_auto_reject_config, name='teams_save_auto_reject_config'),
    path('team-setting/get', teams.team_setting_get, name='teams_team_setting_get'),
    path('team-setting/set', teams.team_setting_set, name='teams_team_setting_set'),
    path('save-activity-report-mode', teams.save_activity_report_mode, name='teams_save_activity_report_mode'),
    path('link-telegram-user', teams.link_telegram_user, name='teams_link_telegram_user'),
    path('get-team-cron-config', teams.get_team_cron_config, name='teams_get_team_cron_config'),
    path('set-team-cron-job', teams.set_team_cron_job, name='teams_set_team_cron_job'),
    path('get-scheduled-jobs', teams.get_scheduled_jobs, name='teams_get_scheduled_jobs'),
    path('toggle-scheduled-job', teams.toggle_scheduled_job, name='teams_toggle_scheduled_job'),
    path('telegram-pair/start', telegram_pair.telegram_pair_start, name='telegram_pair_telegram_pair_start'),
    path('telegram-pair/status', telegram_pair.telegram_pair_status, name='telegram_pair_telegram_pair_status'),
    path('telegram-pair/disconnect', telegram_pair.telegram_pair_disconnect, name='telegram_pair_telegram_pair_disconnect'),
    path('telegram/link-me', telegram_pair.telegram_link_me, name='telegram_pair_telegram_link_me'),
    path('telegram-pair/cancel', telegram_pair.telegram_pair_cancel, name='telegram_pair_telegram_pair_cancel'),
    path('get-semester-schedule', schedule.get_semester_schedule, name='schedule_get_semester_schedule'),
    path('save-semester-schedule', schedule.save_semester_schedule, name='schedule_save_semester_schedule'),
    path('activity-schedule/get', schedule.activity_schedule_get, name='schedule_activity_schedule_get'),
    path('activity-schedule/save', schedule.activity_schedule_save, name='schedule_activity_schedule_save'),
    path('save-activity-report-schedule', schedule.save_activity_report_schedule, name='schedule_save_activity_report_schedule'),
    path('save-current-schedule-config', schedule.save_current_schedule_config, name='schedule_save_current_schedule_config'),
    path('save-activity-coord-config', schedule.save_activity_coord_config, name='schedule_save_activity_coord_config'),
    path('trigger-activity-coord', schedule.trigger_activity_coord, name='schedule_trigger_activity_coord'),
    path('trigger-current-schedule', schedule.trigger_current_schedule, name='schedule_trigger_current_schedule'),
    path('trigger-activity-report', schedule.trigger_activity_report, name='schedule_trigger_activity_report'),
    path('test-activity-report', schedule.test_activity_report, name='schedule_test_activity_report'),
    path('board/manage', board.board_manage, name='board_board_manage'),
    path('post/manage', board.post_manage, name='board_post_manage'),
    path('post/interact', board.post_interact, name='board_post_interact'),
    path('comment/manage', board.comment_manage, name='board_comment_manage'),
    path('storage/upload', storage.storage_upload, name='storage_storage_upload'),
    path('storage/image', storage.storage_image, name='storage_storage_image'),
    path('manage-ministry-categories', ministry.manage_ministry_categories, name='ministry_manage_ministry_categories'),
    path('manage-notification-times', ministry.manage_notification_times, name='ministry_manage_notification_times'),
    path('get-admin-audit-log', admin_audit_log.get_admin_audit_log, name='admin_audit_log_get_admin_audit_log'),
    path('cron-logs', admin_audit_log.cron_logs, name='admin_audit_log_cron_logs'),
    path('preview-activity-coord', preview.preview_activity_coord, name='preview_preview_activity_coord'),
    path('preview-current-schedule', preview.preview_current_schedule, name='preview_preview_current_schedule'),
    path('preview-activity-report', preview.preview_activity_report, name='preview_preview_activity_report'),
    path('submit-prayer', prayer.submit_prayer, name='prayer_submit_prayer'),
    path('lock/acquire', locks.lock_acquire, name='locks_lock_acquire'),
    path('lock/heartbeat', locks.lock_heartbeat, name='locks_lock_heartbeat'),
    path('lock/release', locks.lock_release, name='locks_lock_release'),
    path('get-dolyo-list', dolyo.get_dolyo_list, name='dolyo_get_dolyo_list'),
    path('register-dolyo', dolyo.register_dolyo, name='dolyo_register_dolyo'),
    path('update-dolyo', dolyo.update_dolyo, name='dolyo_update_dolyo'),
    path('add-dolyo-action', dolyo.add_dolyo_action, name='dolyo_add_dolyo_action'),
    path('delete-dolyo-action', dolyo.delete_dolyo_action, name='dolyo_delete_dolyo_action'),
    path('delete-dolyo', dolyo.delete_dolyo, name='dolyo_delete_dolyo'),
    path('dolyo-match-result', dolyo.dolyo_match_result, name='dolyo_dolyo_match_result'),
    path('dolyo-approval', dolyo.dolyo_approval, name='dolyo_dolyo_approval'),
    path('submit-dolyo-habjaeyang', dolyo.submit_dolyo_habjaeyang, name='dolyo_submit_dolyo_habjaeyang'),
    path('reset-dolyo-result', dolyo.reset_dolyo_result, name='dolyo_reset_dolyo_result'),
    path('admin/users/list', admin_users.admin_users_list, name='admin_users_admin_users_list'),
    path('admin/users/meta', admin_users.admin_users_meta, name='admin_users_admin_users_meta'),
    path('admin/users/create', admin_users.admin_users_create, name='admin_users_admin_users_create'),
    path('admin/users/update', admin_users.admin_users_update, name='admin_users_admin_users_update'),
    path('admin/users/bulk-update', admin_users.admin_users_bulk_update, name='admin_users_admin_users_bulk_update'),
    path('admin/users/swap-teams', admin_users.admin_users_swap_teams, name='admin_users_admin_users_swap_teams'),
    path('intake/sheet-meta', intake_sync.intake_sheet_meta, name='intake_sync_intake_sheet_meta'),
    path('intake/sheet-tab-rows', intake_sync.intake_sheet_tab_rows, name='intake_sync_intake_sheet_tab_rows'),
    path('intake/save-config', intake_sync.intake_save_config, name='intake_sync_intake_save_config'),
    path('intake/list-configs', intake_sync.intake_list_configs, name='intake_sync_intake_list_configs'),
    path('intake/delete-config', intake_sync.intake_delete_config, name='intake_sync_intake_delete_config'),
    path('intake/sync-now', intake_sync.intake_sync_now, name='intake_sync_intake_sync_now'),
    path('intake/list-prospects', intake_sync.intake_list_prospects, name='intake_sync_intake_list_prospects'),
    path('intake/save-row', intake_sync.intake_save_row, name='intake_sync_intake_save_row'),
    path('intake/delete-row', intake_sync.intake_delete_row, name='intake_sync_intake_delete_row'),
    path('intake/events', intake_sync.intake_events, name='intake_sync_intake_events'),
    path('intake/assign-manager', intake_sync.intake_assign_manager, name='intake_sync_intake_assign_manager'),
    path('intake/dup-resolve', intake_sync.intake_dup_resolve, name='intake_sync_intake_dup_resolve'),
    path('intake/drive-notify', intake_webhook.intake_drive_notify, name='intake_webhook_intake_drive_notify'),
    path('feedback-slots/list', feedback.feedback_slots_list, name='feedback_feedback_slots_list'),
    path('feedback-slots/create', feedback.feedback_slots_create, name='feedback_feedback_slots_create'),
    path('feedback-slots/delete', feedback.feedback_slots_delete, name='feedback_feedback_slots_delete'),
    path('feedback-slots/book', feedback.feedback_slots_book, name='feedback_feedback_slots_book'),
    path('feedback-slots/cancel', feedback.feedback_slots_cancel, name='feedback_feedback_slots_cancel'),
    path('feedback-slots/pass-list', feedback.feedback_slots_pass_list, name='feedback_feedback_slots_pass_list'),
    path('feedback-slots/result', feedback.feedback_slots_result, name='feedback_feedback_slots_result'),
    path('shed/users', shed_users.shed_users, name='shed_users_shed_users'),
    path('shed/report', shed_report.shed_report, name='shed_report_shed_report'),
    path('shared-leads/notify', shared_leads_notify.shared_leads_notify, name='shared_leads_notify_shared_leads_notify'),
]

internal_urlpatterns = [
    path('telegram/pair-complete', telegram_pair_internal.telegram_pair_complete, name='telegram_pair_internal_telegram_pair_complete'),
    path('telegram/delete-shared-lead', shared_leads_claim.telegram_delete_shared_lead, name='shared_leads_claim_telegram_delete_shared_lead'),
    path('telegram/restore-shared-lead', shared_leads_claim.telegram_restore_shared_lead, name='shared_leads_claim_telegram_restore_shared_lead'),
    path('telegram/claim-shared-lead', shared_leads_claim.telegram_claim_shared_lead, name='shared_leads_claim_telegram_claim_shared_lead'),
    path('sheet-sync', sheet_sync.sheet_sync, name='sheet_sync_sheet_sync'),
    path('telegram/callback', internal_telegram.telegram_callback, name='internal_telegram_telegram_callback'),
]

internal_cron_urlpatterns = [
    path('broadcast-status', cron_internal.broadcast_status, name='cron_internal_broadcast_status'),
    path('send-prayer', cron_internal.send_prayer, name='cron_internal_send_prayer'),
    path('send-stats', cron_internal.send_stats, name='cron_internal_send_stats'),
    path('update-stats', cron_internal.update_stats, name='cron_internal_update_stats'),
    path('send-checkin', cron_internal.send_checkin, name='cron_internal_send_checkin'),
    path('send-activity-coord', cron_internal.send_activity_coord, name='cron_internal_send_activity_coord'),
    path('send-morning-briefing', cron_internal.send_morning_briefing, name='cron_internal_send_morning_briefing'),
    path('send-current-schedule', cron_internal.send_current_schedule, name='cron_internal_send_current_schedule'),
    path('send-activity-report', cron_internal.send_activity_report, name='cron_internal_send_activity_report'),
    path('send-weekly-report', cron_internal.send_weekly_report, name='cron_internal_send_weekly_report'),
    path('send-prospect-dashboard', cron_internal.send_prospect_dashboard, name='cron_internal_send_prospect_dashboard'),
    path('update-prospect-dashboard', cron_internal.update_prospect_dashboard, name='cron_internal_update_prospect_dashboard'),
    path('send-feedback-dashboard', cron_internal.send_feedback_dashboard, name='cron_internal_send_feedback_dashboard'),
    path('send-matching-dashboard', cron_internal.send_matching_dashboard, name='cron_internal_send_matching_dashboard'),
    path('update-matching-dashboard', cron_internal.update_matching_dashboard, name='cron_internal_update_matching_dashboard'),
    path('send-return-home', cron_internal.send_return_home, name='cron_internal_send_return_home'),
    path('sync-pii-hash', cron_internal.sync_pii_hash, name='cron_internal_sync_pii_hash'),
    path('ttl-pii-hash', cron_internal.ttl_pii_hash, name='cron_internal_ttl_pii_hash'),
    path('update-sheet-dashboard', cron_internal.update_sheet_dashboard, name='cron_internal_update_sheet_dashboard'),
    path('send-sheet-dashboard', cron_internal.send_sheet_dashboard, name='cron_internal_send_sheet_dashboard'),
    path('update-talk-dashboard', cron_internal.update_talk_dashboard, name='cron_internal_update_talk_dashboard'),
    path('send-talk-dashboard', cron_internal.send_talk_dashboard, name='cron_internal_send_talk_dashboard'),
    path('sync-intake', cron_internal.sync_intake, name='cron_internal_sync_intake'),
    path('logs', cron_internal.logs, name='cron_internal_logs'),
    path('send-shed-unified-dashboard', cron_internal.send_shed_unified_dashboard, name='cron_internal_send_shed_unified_dashboard'),
    path('update-shed-unified-dashboard', cron_internal.update_shed_unified_dashboard, name='cron_internal_update_shed_unified_dashboard'),
    path('send-shed-tm-dashboard', cron_internal.send_shed_tm_dashboard, name='cron_internal_send_shed_tm_dashboard'),
    path('update-shed-tm-dashboard', cron_internal.update_shed_tm_dashboard, name='cron_internal_update_shed_tm_dashboard'),
    path('send-shed-sched-dashboard', cron_internal.send_shed_sched_dashboard, name='cron_internal_send_shed_sched_dashboard'),
    path('update-shed-sched-dashboard', cron_internal.update_shed_sched_dashboard, name='cron_internal_update_shed_sched_dashboard'),
    path('send-shed-246-dashboard', cron_internal.send_shed_246_dashboard, name='cron_internal_send_shed_246_dashboard'),
    path('update-shed-246-dashboard', cron_internal.update_shed_246_dashboard, name='cron_internal_update_shed_246_dashboard'),
    path('send-shed-246-tm-dashboard', cron_internal.send_shed_246_tm_dashboard, name='cron_internal_send_shed_246_tm_dashboard'),
    path('update-shed-246-tm-dashboard', cron_internal.update_shed_246_tm_dashboard, name='cron_internal_update_shed_246_tm_dashboard'),
    path('send-shed-246-sched-dashboard', cron_internal.send_shed_246_sched_dashboard, name='cron_internal_send_shed_246_sched_dashboard'),
    path('update-shed-246-sched-dashboard', cron_internal.update_shed_246_sched_dashboard, name='cron_internal_update_shed_246_sched_dashboard'),
]
